defaults:
  - ppo_trainer
  - _self_

data:
  train_files: IF-RL-train.parquet
  val_files: IF-RL-train.parquet 
  train_batch_size: 128
  prompt_key: prompt
  max_prompt_length: 5000
  max_response_length: 4000

actor_rollout_ref:
  hybrid_engine: true

  model:
    path: Qwen/Qwen2.5-1.5B-Instruct
    use_remove_padding: true
    enable_gradient_checkpointing: true

  actor:
    use_kl_loss: false
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    loss_agg_mode: "token-mean"
    ppo_mini_batch_size: 2048
    ppo_micro_batch_size_per_gpu: 1
    ppo_epochs: 1
    entropy_coeff: 0.0
    optim:
      lr: 3e-6
      betas: [0.9, 0.95]

  rollout:
    name: vllm
    temperature: 1.0
    top_p: 1.0
    top_k: -1
    n: 16
    log_prob_micro_batch_size_per_gpu: 1
    gpu_memory_utilization: 0.25
    max_model_len: 9000

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
  rollout_correction:
    rollout_is: null
    rollout_rs: null
    bypass_mode: false
    loss_type: ppo_clip
  filter_groups:
    enable: true
    metric: acc
    max_num_gen_batches: 10

reward:
  reward_manager:
    name: dapo
  reward_kwargs:
    max_resp_len: 4000
    overlong_buffer_cfg:
      enable: true
      len: 512
      penalty_factor: 1.0
      log: true

custom_reward_function:
  path: ./reward.py
  name: if_reward_fn

trainer:
  total_training_steps: 180
  save_freq: 10
  val_before_train: false
  test_freq: -1
  default_local_dir: ./if_rl_verl_binary_checkpoints
  project_name: IF-RL
  experiment_name: if_rl_verl
  logger: ['wandb']
  nnodes: 1
  n_gpus_per_node: 1